trigger:
- develop # Pipeline sẽ tự chạy khi bạn push code lên branch main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: android-release-vars # Tên Variable Group bạn tạo trên Library

steps:
# 1. Tải file Keystore (.jks) từ Secure Files
- task: DownloadSecureFile@1
  name: androidKeystore
  inputs:
    secureFile: 'cali-gym-keystore.jks'

# 2. Tải file Service Account (.json) từ Secure Files
- task: DownloadSecureFile@1
  name: firebaseServiceAccount
  inputs:
    secureFile: 'cali-gym-35f385f2c4e9.json'

- task: Cache@2
  displayName: 'Cache Gradle'
  inputs:
    key: 'gradle | "$(Agent.OS)" | android/build.gradle.kts'
    restoreKeys: |
      gradle | "$(Agent.OS)"
    path: $(HOME)/.gradle

- task: Cache@2
  displayName: 'Cache Flutter SDK and Pub'
  inputs:
    key: 'flutter | "$(Agent.OS)" | pubspec.lock'
    restoreKeys: |
      flutter | "$(Agent.OS)"
    path: $(HOME)/.pub-cache

# 3. Cài đặt Flutter SDK
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

# 4. Lấy các thư viện (pub get)
- task: FlutterCommand@0
  displayName: 'Flutter Pub Get'
  inputs:
    projectDirectory: '.'
    arguments: 'pub get'

# 5. Build APK Release
# Ở đây ta truyền biến KEYSTORE_FILE_PATH vào môi trường để build.gradle.kts đọc được
- task: FlutterCommand@0
  displayName: 'Build APK'
  inputs:
    projectDirectory: '.'
    arguments: 'build apk --release --no-pub --build-number=$(Build.BuildId) --target-platform android-arm64'
  env:
    KEYSTORE_FILE_PATH: $(androidKeystore.secureFilePath)
    # THÊM 3 DÒNG NÀY (Đảm bảo tên biến $(...) khớp với tên trong Variable Group của bạn)
    STORE_PASSWORD: $(storePassword)
    KEY_PASSWORD: $(keyPassword)
    KEY_ALIAS: $(keyAlias)
    CHOKIDAR_USEPOLLING: 'true'

# 6. Đẩy file APK lên Firebase App Distribution
- task: FirebaseAppDistribution@5
  displayName: 'Upload to Firebase'
  inputs:
    appId: '$(FIREBASE_APP_ID)'
    privateKeyPath: '$(firebaseServiceAccount.secureFilePath)'
    filePath: '$(Build.SourcesDirectory)/build/app/outputs/flutter-apk/app-release.apk'
    testerGroups: 'internal-tester'
    releaseNotes: 'Cập nhật tự động từ Azure DevOps. Build ID: $(Build.BuildId)'