// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1ThIV-ubdx2DuttaSFNn0WZd1I9aglc',
    appId: '1:591343566903:web:c885238126fb4a93857fb2',
    messagingSenderId: '591343566903',
    projectId: 'cali-gym-915a7',
    authDomain: 'cali-gym-915a7.firebaseapp.com',
    storageBucket: 'cali-gym-915a7.firebasestorage.app',
    measurementId: 'G-SKR47CEW15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hHyIbA6EfWf3pA6SB_5bezO5h6C7sV4',
    appId: '1:591343566903:android:5d732d95ba5d3ed4857fb2',
    messagingSenderId: '591343566903',
    projectId: 'cali-gym-915a7',
    storageBucket: 'cali-gym-915a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_MCk0Ohrhd0jAImDw73VM5rP_ykd-AM',
    appId: '1:591343566903:ios:9f3739d782c79386857fb2',
    messagingSenderId: '591343566903',
    projectId: 'cali-gym-915a7',
    storageBucket: 'cali-gym-915a7.firebasestorage.app',
    iosBundleId: 'com.caligym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_MCk0Ohrhd0jAImDw73VM5rP_ykd-AM',
    appId: '1:591343566903:ios:9f3739d782c79386857fb2',
    messagingSenderId: '591343566903',
    projectId: 'cali-gym-915a7',
    storageBucket: 'cali-gym-915a7.firebasestorage.app',
    iosBundleId: 'com.caligym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu1ThIV-ubdx2DuttaSFNn0WZd1I9aglc',
    appId: '1:591343566903:web:db90c7389a88b655857fb2',
    messagingSenderId: '591343566903',
    projectId: 'cali-gym-915a7',
    authDomain: 'cali-gym-915a7.firebaseapp.com',
    storageBucket: 'cali-gym-915a7.firebasestorage.app',
    measurementId: 'G-K2RZEG5KV5',
  );
}
